name: 03_Produce-data-visualizations
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.9
  - pip==22.0
  - pip: 
    - voila==0.4.0
    - bqplot==0.12.36
    - ipyvolume==0.5.2
    - ipywebrtc==0.6.0
    - ipywidgets==8.0.2
    - scipy==1.9.3
    - matplotlib==3.6.2
    - seaborn==0.12.1
    - statsmodels==0.13.5
    - scikit-learn==1.0.2 
