name: 03_Produce-data-visualizations
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.8.13
  - pip==22.0.4
  - pip: 
    - fastai==2.7.9
    - pydicom==2.3.0
    - kornia==0.6.7
    - scikit-image==0.19.3
    - ipython==7.31.1
    - dtreeviz==1.3.7
    - ipywidgets==7.6.5
    - opencv-python==4.6.0.66
    - spacy==2.3.5
    - fastai-minima==0.0.9
    - gdown==4.2.1
    - voila==0.3.6
    - language-tool-python==2.6.1
